### ISSUE TITLE
Research issue with delta = 1 in "Changing styling from 1200 px to 900 and back, result stays the same" test

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-board#121]
Delta was 1 and changed to 4 due to failures after updating tested browsers

**Comment by web-padawan** [comment]
Still happens on iOS Simulator:

```
redraw > nested row > should have the same size after changing from 1200px to 900px and back (failed on iPhone X Simulator iphone 14.0)
      AssertionError: expected 31 to be close to 28 +/- 1
        at r (node_modules/@esm-bundle/chai/node_modules/chai/chai.js:9549:21)
        at http://10.1.0.4:8000/node_modules/ (esm-bundle/chai/esm/chai.js:98:1456)
        at S (node_modules/@esm-bundle/chai/node_modules/chai/chai.js:3338:8)
        at c (node_modules/@esm-bundle/chai/node_modules/chai/chai.js:7860:30)
```
